# Generated by Django 5.0 on 2024-01-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='itemname', max_length=50)),
                ('pictures', models.ImageField(default='itempic.jpg', upload_to='item_pictures')),
            ],
        ),
    ]
