# Generated by Django 5.0 on 2024-12-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='categories',
            new_name='AllCategories_cake',
        ),
        migrations.AddField(
            model_name='cart',
            name='net_weight',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
