# Generated by Django 5.0 on 2024-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_cart_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='AllCategories_cake',
        ),
        migrations.AddField(
            model_name='cart',
            name='cake_category',
            field=models.CharField(default='generic_cake', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='cake_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='net_weight',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
