# Generated by Django 5.0 on 2024-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_cart_allcategories_cake_cart_cake_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempictures',
            name='pictures',
            field=models.ImageField(default='item_pic.jpg', upload_to='item_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures'),
        ),
    ]
