# Generated by Django 5.0 on 2023-12-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla! Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur? Iusto architecto et nesciunt earum adipisci illum!', max_length=500),
        ),
    ]
