# Generated by Django 5.0 on 2024-04-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_item_user_item_added_by_alter_item_rest_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_code', models.IntegerField(default=50)),
                ('trend_name', models.CharField(max_length=100)),
                ('trend_desc', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti numquam suscipit itaque voluptas non ea voluptatibus assumenda aspernatur at tempora deserunt, velit quam, ex asperiores provident nisi. Minus, unde!')),
                ('category', models.CharField(choices=[('PC', 'Pinata Cakes'), ('PUC', 'Pull Me Up Cakes'), ('BC', 'Bomb Cakes'), ('CSB', 'Cake Surprise Box')], max_length=3)),
            ],
        ),
    ]
