# Generated by Django 5.0 on 2024-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='trend_desc',
        ),
        migrations.AddField(
            model_name='trending',
            name='trend_image',
            field=models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='trending cakes'),
        ),
    ]
