# Generated by Django 5.0 on 2024-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_trending_category_remove_trending_trend_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.IntegerField(default=50)),
                ('design_name', models.CharField(max_length=100)),
                ('design_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='designing cakes')),
            ],
        ),
    ]
