# Generated by Django 5.0 on 2024-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_designing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_code', models.IntegerField(default=50)),
                ('dessert_name', models.CharField(max_length=100)),
                ('dessert_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='desserts')),
            ],
        ),
    ]
