# Generated by Django 5.0 on 2024-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GH', 'Gift Hampers'), ('HC', 'Heart-Shaped Cakes'), ('Wed', 'Wedding Cakes'), ('PC', 'Photo Cakes'), ('TC', 'Tea Cakes & Cookies'), ('GC', 'Gourmet Cakes'), ('EC', 'Eggless Cakes')], max_length=3),
        ),
    ]
