# Generated by Django 5.0 on 2024-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_category_category_title_alter_category_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GC', 'Gourmet Cakes'), ('Wed', 'Wedding Cakes'), ('PC', 'Photo Cakes'), ('EC', 'Eggless Cakes'), ('HC', 'Heart-Shaped Cakes'), ('TC', 'Tea Cakes & Cookies'), ('GH', 'Gift Hampers')], max_length=3),
        ),
    ]
