# Generated by Django 5.0 on 2024-04-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_category_category_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_code', models.IntegerField(default=30)),
                ('flavour_name', models.CharField(max_length=100)),
                ('flavour_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('flavour_price', models.IntegerField()),
                ('flavour_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='flavour')),
                ('flavour', models.CharField(choices=[('BC', 'Blackforest Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('CC', 'Chocolate Cakes'), ('BSC', 'Butterscotch Cakes'), ('FC', 'Fruit Cakes'), ('SC', 'Strawberry Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('EC', 'Eggless Cakes'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes')], max_length=3),
        ),
    ]
