# Generated by Django 5.0 on 2024-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_flavour_alter_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GC', 'Gourmet Cakes'), ('HC', 'Heart-Shaped Cakes'), ('EC', 'Eggless Cakes'), ('TC', 'Tea Cakes & Cookies'), ('Wed', 'Wedding Cakes'), ('GH', 'Gift Hampers'), ('PC', 'Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BSC', 'Butterscotch Cakes'), ('BC', 'Blackforest Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('FC', 'Fruit Cakes')], max_length=3),
        ),
    ]
