# Generated by Django 5.0 on 2024-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_category_categories_alter_flavour_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GC', 'Gourmet Cakes'), ('PC', 'Photo Cakes'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('Wed', 'Wedding Cakes'), ('EC', 'Eggless Cakes'), ('GH', 'Gift Hampers')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('BC', 'Blackforest Cakes'), ('BSC', 'Butterscotch Cakes'), ('FC', 'Fruit Cakes')], max_length=3),
        ),
    ]
