# Generated by Django 5.0 on 2024-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_alter_category_categories_alter_flavour_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_code', models.IntegerField(default=30)),
                ('kids_name', models.CharField(max_length=100)),
                ('kids_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('kids_price', models.IntegerField()),
                ('kids_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='kids')),
                ('kids', models.CharField(choices=[('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('SHC', 'SuperHero Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GC', 'Gourmet Cakes'), ('PC', 'Photo Cakes'), ('Wed', 'Wedding Cakes'), ('GH', 'Gift Hampers'), ('EC', 'Eggless Cakes'), ('HC', 'Heart-Shaped Cakes'), ('TC', 'Tea Cakes & Cookies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('BC', 'Blackforest Cakes'), ('SC', 'Strawberry Cakes'), ('CC', 'Chocolate Cakes')], max_length=3),
        ),
    ]
