# Generated by Django 5.0 on 2024-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_kids_alter_category_categories_alter_flavour_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tending_code', models.IntegerField(default=40)),
                ('trending_name', models.CharField(max_length=100)),
                ('trending_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('trending_price', models.IntegerField()),
                ('trending_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='trending')),
                ('trending', models.CharField(choices=[('PC', 'Pinata Cakes'), ('PMC', 'Pull Me Up Cakes'), ('SCB', 'Suprise Cake Box'), ('BC', 'Bomb Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tea Cakes & Cookies'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('Wed', 'Wedding Cakes'), ('HC', 'Heart-Shaped Cakes'), ('EC', 'Eggless Cakes'), ('GC', 'Gourmet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('PC', 'Pineapple Cakes'), ('RC', 'Red Velvet Cakes'), ('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes'), ('BC', 'Blackforest Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes')], max_length=3),
        ),
    ]
