# Generated by Django 5.0 on 2024-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_occasional_alter_category_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designing_code', models.IntegerField(default=60)),
                ('designing_name', models.CharField(max_length=100)),
                ('designing_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('designing_price', models.IntegerField()),
                ('designing_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='designing')),
                ('designing', models.CharField(choices=[('BSC', 'Baby Shower Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('JTC', 'Jungle Theme Cakes'), ('CTC', 'Cricket Theme Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GH', 'Gift Hampers'), ('HC', 'Heart-Shaped Cakes'), ('TC', 'Tea Cakes & Cookies'), ('PC', 'Photo Cakes'), ('EC', 'Eggless Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('CC', 'Chocolate Cakes'), ('BC', 'Blackforest Cakes'), ('PC', 'Pineapple Cakes'), ('FC', 'Fruit Cakes'), ('RC', 'Red Velvet Cakes'), ('SC', 'Strawberry Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('SHC', 'SuperHero Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('BC', 'Bomb Cakes'), ('PC', 'Pinata Cakes'), ('PMC', 'Pull Me Up Cakes')], max_length=3),
        ),
    ]
