# Generated by Django 5.0 on 2024-04-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_birthday_alter_category_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_code', models.IntegerField(default=80)),
                ('anniversary_name', models.CharField(max_length=100)),
                ('anniversary_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('anniversary_price', models.IntegerField()),
                ('anniversary_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='anniversary')),
                ('anniversary', models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('SBC', 'Special Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('BC', '1st Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('EC', 'Eggless Cakes'), ('GC', 'Gourmet Cakes'), ('HC', 'Heart-Shaped Cakes'), ('TC', 'Tea Cakes & Cookies'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('Wed', 'Wedding Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('CTC', 'Cricket Theme Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes'), ('ANC', 'Alphabet & Number Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BC', 'Blackforest Cakes'), ('PC', 'Pineapple Cakes'), ('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('BC', 'Bomb Cakes'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
