# Generated by Django 5.0 on 2024-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_anniversary_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert_Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_code', models.IntegerField(default=90)),
                ('dc_name', models.CharField(max_length=100)),
                ('dc_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('dc_price', models.IntegerField()),
                ('dc_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='dessert_cake')),
                ('dessert_cake', models.CharField(choices=[('BN', 'Brownies'), ('PS', 'Pastries'), ('CC', 'Cup Cakes'), ('JC', 'Jar Cakes')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('APC', 'Anniversary Photo Cakes'), ('25A', '25th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('50A', '50th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BC', '1st Birthday Cakes'), ('SBC', 'Special Birthday Cakes'), ('BPC', 'Birthday Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('EC', 'Eggless Cakes'), ('GH', 'Gift Hampers'), ('HC', 'Heart-Shaped Cakes'), ('Wed', 'Wedding Cakes'), ('TC', 'Tea Cakes & Cookies'), ('PC', 'Photo Cakes'), ('GC', 'Gourmet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('ANC', 'Alphabet & Number Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes'), ('CTC', 'Cricket Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('PC', 'Pineapple Cakes'), ('RC', 'Red Velvet Cakes'), ('BC', 'Blackforest Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('SHC', 'SuperHero Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('PC', 'Pinata Cakes'), ('PMC', 'Pull Me Up Cakes'), ('BC', 'Bomb Cakes')], max_length=3),
        ),
    ]
