# Generated by Django 5.0 on 2024-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_dessert_cake_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='trend_type',
            field=models.CharField(default='trend', max_length=50),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('SBC', 'Special Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('BC', '1st Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('Wed', 'Wedding Cakes'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('GC', 'Gourmet Cakes'), ('EC', 'Eggless Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('JC', 'Jar Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies'), ('CC', 'Cup Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes'), ('RC', 'Red Velvet Cakes'), ('SC', 'Strawberry Cakes'), ('CC', 'Chocolate Cakes'), ('BC', 'Blackforest Cakes'), ('PC', 'Pineapple Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PC', 'Pinata Cakes'), ('PMC', 'Pull Me Up Cakes')], max_length=3),
        ),
    ]
