# Generated by Django 5.0 on 2024-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_trending_trend_type_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designing',
            name='design_desc',
            field=models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500),
        ),
        migrations.AddField(
            model_name='desserts',
            name='dessert_type',
            field=models.CharField(default='desserts', max_length=50),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('APC', 'Anniversary Photo Cakes'), ('50A', '50th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BC', '1st Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('SBC', 'Special Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('HC', 'Heart-Shaped Cakes'), ('GH', 'Gift Hampers'), ('TC', 'Tea Cakes & Cookies'), ('EC', 'Eggless Cakes'), ('Wed', 'Wedding Cakes'), ('PC', 'Photo Cakes'), ('GC', 'Gourmet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('JTC', 'Jungle Theme Cakes'), ('BSC', 'Baby Shower Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('CTC', 'Cricket Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('BN', 'Brownies'), ('CC', 'Cup Cakes'), ('JC', 'Jar Cakes'), ('PS', 'Pastries')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BC', 'Blackforest Cakes'), ('BSC', 'Butterscotch Cakes'), ('PC', 'Pineapple Cakes'), ('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('SHC', 'SuperHero Cakes'), ('PC', 'Princess Cakes'), ('CTC', 'Cartoon Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('MFC', 'Mothers & Fathers Day Cakes'), ('DC', 'Doctors Dya Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PMC', 'Pull Me Up Cakes'), ('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
