# Generated by Django 5.0 on 2024-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_designing_design_desc_desserts_dessert_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designing',
            name='design_desc',
        ),
        migrations.AddField(
            model_name='designing',
            name='design_type',
            field=models.CharField(default='design', max_length=50),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes'), ('50A', '50th Anniversary Cakes'), ('25A', '25th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('SBC', 'Special Birthday Cakes'), ('BC', '1st Birthday Cakes'), ('BPC', 'Birthday Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('Wed', 'Wedding Cakes'), ('PC', 'Photo Cakes'), ('TC', 'Tea Cakes & Cookies'), ('GH', 'Gift Hampers'), ('HC', 'Heart-Shaped Cakes'), ('GC', 'Gourmet Cakes'), ('EC', 'Eggless Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('ANC', 'Alphabet & Number Cakes'), ('CTC', 'Cricket Theme Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('PS', 'Pastries'), ('JC', 'Jar Cakes'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('CC', 'Chocolate Cakes'), ('RC', 'Red Velvet Cakes'), ('SC', 'Strawberry Cakes'), ('FC', 'Fruit Cakes'), ('PC', 'Pineapple Cakes'), ('BSC', 'Butterscotch Cakes'), ('BC', 'Blackforest Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('SHC', 'SuperHero Cakes'), ('CC', 'Car Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('MFC', 'Mothers & Fathers Day Cakes'), ('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
