# Generated by Django 5.0 on 2024-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_remove_designing_design_desc_designing_design_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_code', models.IntegerField(default=90)),
                ('ac_name', models.CharField(max_length=100)),
                ('ac_desc', models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore natus dolorum nulla. Ut placeat fuga iure dolor voluptates velit asperiores nemo voluptatem pariatur. Iusto architecto et nesciunt earum adipisci illum.', max_length=500)),
                ('ac_price', models.IntegerField()),
                ('ac_image', models.ImageField(default='https://www.thatlittlecakeshop.co.nz/cdn/shop/products/E6A577FE-B2BE-4ED2-B9BD-17041EE271EC.jpg?v=1630311125', upload_to='allcategory_cake')),
            ],
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('APC', 'Anniversary Photo Cakes'), ('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BPC', 'Birthday Photo Cakes'), ('BC', '1st Birthday Cakes'), ('SBC', 'Special Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tea Cakes & Cookies'), ('GH', 'Gift Hampers'), ('EC', 'Eggless Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes'), ('PC', 'Photo Cakes'), ('HC', 'Heart-Shaped Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('CTC', 'Cricket Theme Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('BN', 'Brownies'), ('JC', 'Jar Cakes'), ('CC', 'Cup Cakes'), ('PS', 'Pastries')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('CC', 'Chocolate Cakes'), ('SC', 'Strawberry Cakes'), ('BC', 'Blackforest Cakes'), ('RC', 'Red Velvet Cakes'), ('FC', 'Fruit Cakes'), ('PC', 'Pineapple Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('BC', 'Bomb Cakes'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
