# Generated by Django 5.0 on 2024-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0030_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('50A', '50th Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes'), ('1AC', '1st Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('EC', 'Eggless Cakes'), ('GC', 'Gourmet Cakes'), ('GH', 'Gift Hampers'), ('PC', 'Photo Cakes'), ('HC', 'Heart-Shaped Cakes'), ('TC', 'Tea Cakes & Cookies'), ('Wed', 'Wedding Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('BSC', 'Baby Shower Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('JTC', 'Jungle Theme Cakes'), ('CTC', 'Cricket Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies'), ('JC', 'Jar Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('SC', 'Strawberry Cakes'), ('BSC', 'Butterscotch Cakes'), ('PC', 'Pineapple Cakes'), ('BC', 'Blackforest Cakes'), ('CC', 'Chocolate Cakes'), ('RC', 'Red Velvet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes'), ('SHC', 'SuperHero Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('MFC', 'Mothers & Fathers Day Cakes'), ('DC', 'Doctors Dya Cake'), ('TC', 'Teachers Day Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes'), ('BC', 'Bomb Cakes')], max_length=3),
        ),
    ]
