# Generated by Django 5.0 on 2024-12-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes'), ('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BPC', 'Birthday Photo Cakes'), ('SBC', 'Special Birthday Cakes'), ('BC', '1st Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GH', 'Gift Hampers'), ('PC', 'Photo Cakes'), ('TC', 'Tea Cakes & Cookies'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes'), ('EC', 'Eggless Cakes'), ('HC', 'Heart-Shaped Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('CTC', 'Cricket Theme Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('JTC', 'Jungle Theme Cakes'), ('BSC', 'Baby Shower Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('PS', 'Pastries'), ('CC', 'Cup Cakes'), ('BN', 'Brownies'), ('JC', 'Jar Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('PC', 'Pineapple Cakes'), ('BSC', 'Butterscotch Cakes'), ('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('BC', 'Blackforest Cakes'), ('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('CC', 'Car Cakes'), ('PC', 'Princess Cakes'), ('SHC', 'SuperHero Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes'), ('TC', 'Teachers Day Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PC', 'Pinata Cakes'), ('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes')], max_length=3),
        ),
    ]
