# Generated by Django 5.0 on 2024-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_anniversary_anniversary_price_1kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('APC', 'Anniversary Photo Cakes'), ('50A', '50th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BC', '1st Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('SBC', 'Special Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('EC', 'Eggless Cakes'), ('GH', 'Gift Hampers'), ('TC', 'Tea Cakes & Cookies'), ('PC', 'Photo Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes'), ('HC', 'Heart-Shaped Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('ANC', 'Alphabet & Number Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes'), ('CTC', 'Cricket Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('JC', 'Jar Cakes'), ('BN', 'Brownies'), ('PS', 'Pastries')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes'), ('PC', 'Pineapple Cakes'), ('BC', 'Blackforest Cakes'), ('CC', 'Chocolate Cakes'), ('RC', 'Red Velvet Cakes'), ('SC', 'Strawberry Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('SHC', 'SuperHero Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('MFC', 'Mothers & Fathers Day Cakes'), ('DC', 'Doctors Dya Cake')], max_length=3),
        ),
    ]
