# Generated by Django 5.0 on 2024-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0036_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='category',
            field=models.CharField(default='name of model', max_length=100),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('SBC', 'Special Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('BC', '1st Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('PC', 'Photo Cakes'), ('GC', 'Gourmet Cakes'), ('Wed', 'Wedding Cakes'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('EC', 'Eggless Cakes'), ('GH', 'Gift Hampers')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('ANC', 'Alphabet & Number Cakes'), ('CTC', 'Cricket Theme Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('JC', 'Jar Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('SC', 'Strawberry Cakes'), ('BC', 'Blackforest Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('CC', 'Chocolate Cakes'), ('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('CC', 'Car Cakes'), ('PC', 'Princess Cakes'), ('CTC', 'Cartoon Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes'), ('TC', 'Teachers Day Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
