# Generated by Django 5.0 on 2024-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_trend_category_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcategories',
            old_name='ac_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='allcategories',
            old_name='ac_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='allcategories',
            old_name='ac_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='anniversary',
            old_name='anniversary_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='anniversary',
            old_name='anniversary_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='anniversary',
            old_name='anniversary_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='birthday_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='birthday_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='birthday_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='designing_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='designing_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='designing_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='flavour',
            old_name='flavour_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='flavour',
            old_name='flavour_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='flavour',
            old_name='flavour_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='kids',
            old_name='kids_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='kids',
            old_name='kids_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='kids',
            old_name='kids_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='occasional',
            old_name='occasion_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='occasional',
            old_name='occasion_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='occasional',
            old_name='occasion_price_500gm',
            new_name='price_500gm',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='trending_price_1kg',
            new_name='price_1kg',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='trending_price_250gm',
            new_name='price_250gm',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='trending_price_500gm',
            new_name='price_500gm',
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('25A', '25th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BC', '1st Birthday Cakes'), ('SBC', 'Special Birthday Cakes'), ('BPC', 'Birthday Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('HC', 'Heart-Shaped Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes'), ('GH', 'Gift Hampers'), ('PC', 'Photo Cakes'), ('TC', 'Tea Cakes & Cookies'), ('EC', 'Eggless Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('BSC', 'Baby Shower Cakes'), ('CTC', 'Cricket Theme Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('JTC', 'Jungle Theme Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('JC', 'Jar Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies'), ('CC', 'Cup Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BC', 'Blackforest Cakes'), ('PC', 'Pineapple Cakes'), ('CC', 'Chocolate Cakes'), ('FC', 'Fruit Cakes'), ('SC', 'Strawberry Cakes'), ('BSC', 'Butterscotch Cakes'), ('RC', 'Red Velvet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('SHC', 'SuperHero Cakes'), ('PC', 'Princess Cakes'), ('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('MFC', 'Mothers & Fathers Day Cakes'), ('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PC', 'Pinata Cakes'), ('BC', 'Bomb Cakes'), ('PMC', 'Pull Me Up Cakes'), ('SCB', 'Suprise Cake Box')], max_length=3),
        ),
    ]
