# Generated by Django 5.0 on 2024-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0038_rename_ac_price_1kg_allcategories_price_1kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BPC', 'Birthday Photo Cakes'), ('BC', '1st Birthday Cakes'), ('SBC', 'Special Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('Wed', 'Wedding Cakes'), ('GH', 'Gift Hampers'), ('EC', 'Eggless Cakes'), ('GC', 'Gourmet Cakes'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('PC', 'Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('JC', 'Jar Cakes'), ('CC', 'Cup Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BSC', 'Butterscotch Cakes'), ('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('SC', 'Strawberry Cakes'), ('BC', 'Blackforest Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('SHC', 'SuperHero Cakes'), ('CC', 'Car Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PC', 'Pinata Cakes'), ('SCB', 'Suprise Cake Box'), ('BC', 'Bomb Cakes'), ('PMC', 'Pull Me Up Cakes')], max_length=3),
        ),
    ]
