# Generated by Django 5.0 on 2024-12-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0039_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('50A', '50th Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BPC', 'Birthday Photo Cakes'), ('SBC', 'Special Birthday Cakes'), ('BC', '1st Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('GH', 'Gift Hampers'), ('EC', 'Eggless Cakes'), ('Wed', 'Wedding Cakes'), ('TC', 'Tea Cakes & Cookies'), ('HC', 'Heart-Shaped Cakes'), ('GC', 'Gourmet Cakes'), ('PC', 'Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('JTC', 'Jungle Theme Cakes'), ('ANC', 'Alphabet & Number Cakes'), ('CTC', 'Cricket Theme Cakes'), ('BSC', 'Baby Shower Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('JC', 'Jar Cakes'), ('PS', 'Pastries'), ('CC', 'Cup Cakes'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('PC', 'Pineapple Cakes'), ('FC', 'Fruit Cakes'), ('CC', 'Chocolate Cakes'), ('BC', 'Blackforest Cakes'), ('RC', 'Red Velvet Cakes'), ('SC', 'Strawberry Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CTC', 'Cartoon Cakes'), ('SHC', 'SuperHero Cakes'), ('CC', 'Car Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('MFC', 'Mothers & Fathers Day Cakes'), ('DC', 'Doctors Dya Cake'), ('TC', 'Teachers Day Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PC', 'Pinata Cakes'), ('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('BC', 'Bomb Cakes')], max_length=3),
        ),
    ]
