# Generated by Django 5.0 on 2024-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0040_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('25A', '25th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes'), ('1AC', '1st Anniversary Cakes'), ('50A', '50th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('SBC', 'Special Birthday Cakes'), ('BC', '1st Birthday Cakes'), ('BPC', 'Birthday Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('HC', 'Heart-Shaped Cakes'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('EC', 'Eggless Cakes'), ('Wed', 'Wedding Cakes'), ('GC', 'Gourmet Cakes'), ('TC', 'Tea Cakes & Cookies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes'), ('CTC', 'Cricket Theme Cakes'), ('ANC', 'Alphabet & Number Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('JC', 'Jar Cakes'), ('PS', 'Pastries'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('BC', 'Blackforest Cakes'), ('SC', 'Strawberry Cakes'), ('CC', 'Chocolate Cakes'), ('FC', 'Fruit Cakes'), ('PC', 'Pineapple Cakes'), ('BSC', 'Butterscotch Cakes'), ('RC', 'Red Velvet Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes'), ('SHC', 'SuperHero Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake'), ('MFC', 'Mothers & Fathers Day Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('BC', 'Bomb Cakes'), ('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
