# Generated by Django 5.0 on 2024-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0042_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('50A', '50th Anniversary Cakes'), ('1AC', '1st Anniversary Cakes'), ('25A', '25th Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.CharField(choices=[('BC', '1st Birthday Cakes'), ('BPC', 'Birthday Photo Cakes'), ('SBC', 'Special Birthday Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tea Cakes & Cookies'), ('GC', 'Gourmet Cakes'), ('EC', 'Eggless Cakes'), ('HC', 'Heart-Shaped Cakes'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('Wed', 'Wedding Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('CTC', 'Cricket Theme Cakes'), ('BSC', 'Baby Shower Cakes'), ('JTC', 'Jungle Theme Cakes'), ('ANC', 'Alphabet & Number Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('CC', 'Cup Cakes'), ('BN', 'Brownies'), ('JC', 'Jar Cakes'), ('PS', 'Pastries')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('FC', 'Fruit Cakes'), ('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('CC', 'Chocolate Cakes'), ('BSC', 'Butterscotch Cakes'), ('BC', 'Blackforest Cakes'), ('PC', 'Pineapple Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('SHC', 'SuperHero Cakes'), ('CTC', 'Cartoon Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='occasional',
            name='occasion',
            field=models.CharField(choices=[('MFC', 'Mothers & Fathers Day Cakes'), ('TC', 'Teachers Day Cake'), ('DC', 'Doctors Dya Cake')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('PMC', 'Pull Me Up Cakes'), ('SCB', 'Suprise Cake Box'), ('PC', 'Pinata Cakes'), ('BC', 'Bomb Cakes')], max_length=3),
        ),
    ]
