# Generated by Django 5.0 on 2024-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0043_alter_anniversary_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='anniversary',
            field=models.CharField(choices=[('1AC', '1st Anniversary Cakes'), ('APC', 'Anniversary Photo Cakes'), ('25A', '25th Anniversary Cakes'), ('50A', '50th Anniversary Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tea Cakes & Cookies'), ('EC', 'Eggless Cakes'), ('GC', 'Gourmet Cakes'), ('PC', 'Photo Cakes'), ('GH', 'Gift Hampers'), ('Wed', 'Wedding Cakes'), ('HC', 'Heart-Shaped Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='design',
            name='designing',
            field=models.CharField(choices=[('BSC', 'Baby Shower Cakes'), ('CTC', 'Cricket Theme Cakes'), ('JTC', 'Jungle Theme Cakes'), ('ANC', 'Alphabet & Number Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dessert_cake',
            name='dessert_cake',
            field=models.CharField(choices=[('PS', 'Pastries'), ('CC', 'Cup Cakes'), ('JC', 'Jar Cakes'), ('BN', 'Brownies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour',
            field=models.CharField(choices=[('SC', 'Strawberry Cakes'), ('RC', 'Red Velvet Cakes'), ('PC', 'Pineapple Cakes'), ('CC', 'Chocolate Cakes'), ('BC', 'Blackforest Cakes'), ('FC', 'Fruit Cakes'), ('BSC', 'Butterscotch Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kids',
            field=models.CharField(choices=[('CC', 'Car Cakes'), ('CTC', 'Cartoon Cakes'), ('SHC', 'SuperHero Cakes'), ('PC', 'Princess Cakes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trending',
            field=models.CharField(choices=[('SCB', 'Suprise Cake Box'), ('PMC', 'Pull Me Up Cakes'), ('BC', 'Bomb Cakes'), ('PC', 'Pinata Cakes')], max_length=3),
        ),
    ]
